---
platform: linux
image: docker:///emccmd/persist-sb
inputs:
- name: cf-persist-service-broker
- name: version-semver
outputs:
- name: promote
run:
  path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
params:
