libstorage:
  host: tcp://file_fake_host:9000
  storage:
    driver: scaleio

scaleio:
  endpoint:             https://file_fake_endpoint/api
  insecure:             true
  useCerts:             false
  userName:             file_fake_user
  password:             file_fake_password
  systemID:             file_fake_sys_id
  systemName:           file_fake_sys_name
  protectionDomainID:   file_fake_protection_domain_id
  protectionDomainName: file_fake_protection_domain_name
  storagePoolName:      file_fake_storage_pool_name
  thinOrThick:          ThinProvisioned
  version:              2.0

