groups:
- name: EMC-Persistence-Broker
  jobs:
  - scaleio-integration
  - isilon-integration
  - scaleio-lifecycle
  - scale-up-cells
  - isilon-lifecycle
  - scale-down-cells
  - promote-candidate

jobs:
- name: scaleio-integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true,       get: cf-persist-service-broker}
  - task: integration
    config:
      platform: linux
      image_resource: &docker
          type: docker-image
          source:
            repository: {{docker_repo}}
            insecure_registries: [{{docker_registry}}]
      params: &integration-params
        TEST_INSTANCE_ID:                     {{test_instance_id}}
        PARSED_INSTANCE_ID:                   {{parsed_instance_id}}
        TEST_SIZE:                            8
        STORAGE_POOL_NAME:                    {{storage_pool_name}}
        BROKER_PASSWORD:                      {{broker_password}}
        BROKER_USERNAME:                      {{broker_username}}
        PORT:                                 9000
        INSECURE:                             true
        LIBSTORAGE_URI:                       {{libstorage_uri}}
        LIB_STOR_SERVICE:                     {{lib_stor_service_scaleio}}
        DIEGO_DRIVER_SPEC:                    {{diego_driver_spec_scaleio}}
        EMC_SERVICE_UUID:                     {{emc_service_uuid}}
        EMC_SERVICE_NAME:                     {{emc_service_name}}
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh

- name: isilon-integration
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
  - task: integration
    config:
      platform: linux
      image_resource: *docker
      params: &integration-params
        TEST_INSTANCE_ID:                     {{test_instance_id}}
        PARSED_INSTANCE_ID:                   {{parsed_instance_id}}
        TEST_SIZE:                            0
        STORAGE_POOL_NAME:                    {{storage_pool_name}}
        BROKER_PASSWORD:                      {{broker_password}}
        BROKER_USERNAME:                      {{broker_username}}
        PORT:                                 9000
        INSECURE:                             true
        LIBSTORAGE_URI:                       {{libstorage_uri}}
        LIB_STOR_SERVICE:                     {{lib_stor_service_isilon}}
        DIEGO_DRIVER_SPEC:                    {{diego_driver_spec_isilon}}
        EMC_SERVICE_UUID:                     {{emc_service_uuid}}
        EMC_SERVICE_NAME:                     {{emc_service_name}}
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh


- name: scaleio-lifecycle
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [scaleio-integration]
    - get: lifecycle-app
    - put: scaleio-lock
      resource: promote-lock
      params: {acquire: true}
  - task: lifecycle
    config:
      image_resource: *docker
      platform: linux
      params: &lifecycle-params
        BROKER_NAME:              {{broker_name}}
        BROKER_PASSWORD:          {{broker_password}}
        BROKER_USERNAME:          {{broker_username}}
        EMC_SERVICE_UUID:         {{emc_service_uuid}}
        EMC_SERVICE_NAME:         {{emc_service_name}}
        CF_ENDPOINT:              {{cf_endpoint}}
        CF_USERNAME:              {{cf_username}}
        CF_PASSWORD:              {{cf_password}}
        CF_ORG:                   {{cf_org}}
        CF_SPACE:                 {{cf_space}}
        CF_SERVICE:               {{emc_service_name}}
        LIBSTORAGE_URI:           {{libstorage_uri}}
        LIB_STOR_SERVICE:         {{lib_stor_service_scaleio}}
        INSECURE:                 true
        DIEGO_DRIVER_SPEC:        {{diego_driver_spec_scaleio}}
        TEST_APP_NAME:            {{test_app_name}}
      inputs:
      - name: cf-persist-service-broker
      - name: lifecycle-app
      run:
        path: cf-persist-service-broker/ci/tasks/scaleio-lifecycle.sh
  - put: promote-lock
    params: {release: scaleio-lock}

- name: scale-up-cells
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [isilon-integration]
  - task: scale-diego
    config:
      image_resource: *docker
      platform: linux
      params: &lifecycle-params
        SCALEIO_MDM_IPS:          {{scaleio_mdm_ips}}
        CI_DIEGOCELL_IPS:         {{ci_diegocell_ips}}
        DIEGO_DEPLOYMENT_NAME:    {{diego_deployment_name}}
        BOSH_DIR:                 {{bosh_dir}}
        BOSH_USER:                {{bosh_user}}
        BOSH_PASS:                {{bosh_pass}}
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/scale-up-cells.sh

- name: isilon-lifecycle
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [scale-up-cells]
    - get: lifecycle-app
  - task: lifecycle
    config:
      image_resource: &docker
      platform: linux
      params: &lifecycle-params
        BROKER_NAME:              {{broker_name}}
        BROKER_PASSWORD:          {{broker_password}}
        BROKER_USERNAME:          {{broker_username}}
        EMC_SERVICE_UUID:         {{emc_service_uuid}}
        EMC_SERVICE_NAME:         {{emc_service_name}}
        CF_ENDPOINT:              {{cf_endpoint}}
        CF_USERNAME:              {{cf_username}}
        CF_PASSWORD:              {{cf_password}}
        CF_ORG:                   {{cf_org}}
        CF_SPACE:                 {{cf_space}}
        CF_SERVICE:               {{emc_service_name}}
        LIBSTORAGE_URI:           {{libstorage_uri}}
        LIB_STOR_SERVICE:         {{lib_stor_service_isilon}}
        INSECURE:                 true
        DIEGO_DRIVER_SPEC:        {{diego_driver_spec_isilon}}
        TEST_APP_NAME:            {{test_app_name}}
        NUM_DIEGO_CELLS:          {{num_diego_cells}}
        APP_MEMORY:               {{app_memory}}
        SCALEIO_MDM_IPS:          {{scaleio_mdm_ips}}
        CI_DIEGOCELL_IPS:         {{ci_diegocell_ips}}
        DIEGO_DEPLOYMENT_NAME:    {{diego_deployment_name}}
        BOSH_DIR:                 {{bosh_dir}}
        BOSH_USER:                {{bosh_user}}
        BOSH_PASS:                {{bosh_pass}}
      inputs:
      - name: cf-persist-service-broker
      - name: lifecycle-app
      run:
        path: cf-persist-service-broker/ci/tasks/isilon-lifecycle.sh

- name: scale-down-cells
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [isilon-lifecycle]
    - put: isilon-lock
      resource: promote-lock
      params: {acquire: true}
  - task: scale-diego
    config:
      image_resource: &docker
      platform: linux
      params: &lifecycle-params
        SCALEIO_MDM_IPS:          {{scaleio_mdm_ips}}
        CI_DIEGOCELL_IPS:         {{ci_diegocell_ips}}
        DIEGO_DEPLOYMENT_NAME:    {{diego_deployment_name}}
        BOSH_DIR:                 {{bosh_dir}}
        BOSH_USER:                {{bosh_user}}
        BOSH_PASS:                {{bosh_pass}}
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/scale-down-cells.sh
  - put: promote-lock
    params: {release: isilon-lock}

- name: promote-candidate
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [scale-down-cells, scaleio-lifecycle]
    - get: version-semver
      trigger: false
      params: {bump: major}
    - put: scaleio-lock
      resource: promote-lock
      params: {acquire: true}
    - put: isilon-lock
      resource: promote-lock
      params: {acquire: true}
  - task: promote
    config:
      platform: linux
      image_resource: *docker
      inputs:
      - name: cf-persist-service-broker
      - name: version-semver
      outputs:
      - name: promote
      run:
        path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
      params: &promote-params
        GITHUB_USER:              {{github_user}}
        GITHUB_EMAIL:             {{github_email}}
  - put: cf-persist-service-broker
    params: {repository: promote/cf-persist-service-broker, rebase: true, tag_prefix: "v", tag: promote/integer_version}
  - put: version-semver
    params: {file: version-semver/number}
  - put: promote-lock
    params: {release: isilon-lock}
  - put: promote-lock
    params: {release: scaleio-lock}

resources:
- name: cf-persist-service-broker
  type: git
  source:
    uri: https://github.com/EMC-Dojo/cf-persist-service-broker.git
    branch: separate_concourse
    username: {{github_user}}
    password: {{github_password}}
    skip_ssl_verification: true

- name: lifecycle-app
  type: git
  source:
    uri: https://github.com/EMC-dojo/kitty.git
    branch: master
    username: {{github_user}}
    password: {{github_password}}
    skip_ssl_verification: true


- name: promote-lock
  type: pool
  source:
    uri: https://github.com/EMC-CMD/ci-promote-lock.git
    branch: master
    username: {{github_user}}
    password: {{github_password}}

- name: version-semver
  type: semver
  source:
    key:               number
    bucket:            {{s3_bucket_name}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
