groups:
- name: EMC-Persistence-Broker
  jobs:
  - ScaleIO-Integration
  - Isilon-Integration
  - CloudFoundry-EMC-Persistence-Lifecycle
  # - promote-candidate

jobs:
- name: ScaleIO-Integration
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
  - task: integration
    config:
      platform: linux
      image_resource:
          type: docker-image
          source:
            repository: {{docker_repo}}
            insecure_registries: [{{docker_registry}}]
      params: &integration-params
        TEST_INSTANCE_ID:                     {{test_instance_id}}
        PARSED_INSTANCE_ID:                   {{parsed_instance_id}}
        TEST_SIZE:                            8
        STORAGE_POOL_NAME:                    {{storage_pool_name}}
        BROKER_PASSWORD:                      {{broker_password}}
        BROKER_USERNAME:                      {{broker_username}}
        BROKER_PORT:                          {{broker_port}}
        INSECURE:                             true
        LIBSTORAGE_URI:                       {{libstorage_uri}}
        LIBSTORAGE_DRIVER_TYPE:               scaleio
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh

- name: Isilon-Integration
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
  - task: integration
    config:
      platform: linux
      image_resource:
          type: docker-image
          source:
            repository: {{docker_repo}}
            insecure_registries: [{{docker_registry}}]
      params: &integration-params
        TEST_INSTANCE_ID:                     {{test_instance_id}}
        PARSED_INSTANCE_ID:                   {{parsed_instance_id}}
        TEST_SIZE:                            0
        STORAGE_POOL_NAME:                    {{storage_pool_name}}
        BROKER_PASSWORD:                      {{broker_password}}
        BROKER_USERNAME:                      {{broker_username}}
        BROKER_PORT:                          {{broker_port}}
        INSECURE:                             true
        LIBSTORAGE_URI:                       {{libstorage_uri}}
        LIBSTORAGE_DRIVER_TYPE:               isilon
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh


- name: CloudFoundry-EMC-Persistence-Lifecycle
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [Isilon-Integration]
  - task: lifecycle
    config:
      image_resource:
          type: docker-image
          source:
            repository: {{docker_repo}}
            insecure_registries: [{{docker_registry}}]
      platform: linux
      params: &lifecycle-params
        BROKER_NAME:              {{broker_name}}
        BROKER_PASSWORD:          {{broker_password}}
        BROKER_USERNAME:          {{broker_username}}
        CF_ENDPOINT:              {{cf_endpoint}}
        CF_USERNAME:              {{cf_username}}
        CF_PASSWORD:              {{cf_password}}
        CF_ORG:                   {{cf_org}}
        CF_SPACE:                 {{cf_space}}
        LIBSTORAGE_URI:           {{libstorage_uri}}
        INSECURE:                 true
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/lifecycle.sh



# - name: promote-candidate
#   serial: true
#   plan:
#   - aggregate:
#     - {trigger: true,   passed: [lifecycle], get: cf-persist-service-broker}
#     - {trigger: false,  get: version-semver,  params: {bump: major}}
#   - task: promote
#     config:
#       platform: linux
#       image_resource:
#           type: docker-image
#           source:
#             repository: {{docker_repo}}
#             insecure_registries: [{{docker_registry}}]
#       inputs:
#       - name: cf-persist-service-broker
#       - name: version-semver
#       outputs:
#       - name: promote
#       run:
#         path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
#       params:
#   - put: cf-persist-service-broker-out
#     params: {repository: promote/cf-persist-service-broker, rebase: true, tag_prefix: "v", tag: promote/integer_version}
#   - put: version-semver
#     params: {file: version-semver/number}


resources:
- name: cf-persist-service-broker
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/cf-persist-service-broker.git
    branch: master

- name: scaleio-acceptance-app
  type: git
  source:
    uri: https://{{github_user}}:{{github_password}}@github.com/EMC-CMD/scaleio-io-test.git
    branch: master

- name: cf-persist-service-broker-out
  type: git
  source:
    uri: '--repo https://{{github_user}}:{{github_password}}@github.com/EMC-Dojo/cf-persist-service-broker.git'
    branch: master

- name: version-semver
  type: semver
  source:
    key:               number
    bucket:            {{s3_bucket_name}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
