jobs:
- name: integration
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
  - task: integration
    file: cf-persist-service-broker/ci/tasks/integration.yml
    params:
      BROKER_USERNAME:                    {{broker_username}}
      BROKER_PASSWORD:                    {{broker_password}}
      LIBSTORAGE_HOST_URL:                {{libstorage_host_url}}
      SCALEIO_ENDPOINT:                   {{scaleio_endpoint}}
      SCALEIO_USERNAME:                   {{scaleio_username}}
      SCALEIO_PASSWORD:                   {{scaleio_password}}
      SCALEIO_SYSTEMID:                   {{scaleio_system_id}}
      SCALEIO_SYSTEMNAME:                 {{scaleio_system_name}}
      SCALEIO_PROTECTIONDOMAIN_ID:        {{scaleio_protectiondomain_id}}
      SCALEIO_PROTECTIONDOMAIN_NAME:      {{scaleio_protection_domain_name}}
      SCALEIO_STORAGEPOOL_NAME:           {{scaleio_storagepool_name}}
      SCALEIO_THINORTHICK:                {{scaleio_thinorthick}}
      SCALEIO_VERSION:                    {{scaleio_version}}

- name: lifecycle
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [integration]
  - task: lifecycle
    file: cf-persist-service-broker/ci/tasks/lifecycle.yml
    params:
      CF_IP:                  {{cf_ip}}
      CF_ENDPOINT:            {{cf_endpoint}}
      CF_USERNAME:            {{cf_username}}
      CF_PASSWORD:            {{cf_password}}
      CF_ORG:                 {{cf_org}}
      CF_SPACE:               {{cf_space}}
      SCALEIO_ENDPOINT:       {{scaleio_endpoint}}
      SCALEIO_USERNAME:       {{scaleio_username}}
      SCALEIO_PASSWORD:       {{scaleio_password}}
      BROKER_USERNAME:        {{broker_username}}
      BROKER_PASSWORD:        {{broker_password}}

- name: promote-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: true,   passed: [lifecycle], get: cf-persist-service-broker}
    - {trigger: false,  get: version-semver,  params: {bump: major}}

  - task: promote
    file: cf-persist-service-broker/ci/tasks/promote-candidate.yml

  - put: cf-persist-service-broker-out
    params: {repository: promote/cf-persist-service-broker, rebase: true, tag_prefix: "v", tag: promote/integer_version}

  - put: version-semver
    params: {file: version-semver/number}

resources:
- name: cf-persist-service-broker
  type: git
  source:
    uri: git@github.com:EMC-CMD/cf-persist-service-broker.git
    branch: master
    private_key: {{github_private_key}}

- name: cf-persist-service-broker-out
  type: git
  source:
    uri: git@github.com:EMC-CMD/cf-persist-service-broker.git
    branch: master
    private_key: {{github_private_key}}

- name: version-semver
  type: semver
  source:
    key:               number
    bucket:            {{s3_bucket_name}}
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
