groups:
- name: EMC-Persistence-Broker
  jobs:
  - scaleio-vats
  - scaleio-integration
  - isilon-vats
  - isilon-integration
  - deploy-cells
  - scaleio-lifecycle
  - isilon-lifecycle
  - promote-broker
  - promote-rexray
  - promote-sdc

jobs:
- name: scaleio-vats
  serial: true
  plan:
  - aggregate:
    - {trigger: true, get: rexray-boshrelease}
    - {trigger: true, get: scaleio-sdc-boshrelease}
    - {trigger: true, get: volman}
  - task: vats
    docker-image: &docker
      platform: linux
      image_resource:
          type: docker-image
          source:
            repository: {{docker_repo}}
            insecure_registries: [{{docker_registry}}]
    config:
      <<: *docker
      inputs:
      - name: scaleio-sdc-boshrelease
      - name: rexray-boshrelease
      - name: volman
      default-params: &vats-params
        BOSH_DIRECTOR_PUBLIC_IP:          {{bosh_director_public_ip}}
        BOSH_PASSWORD:                    {{bosh_password}}
        BOSH_USER:                        {{bosh_user}}
        VATS_DEPLOYMENT_PASSWORD:         {{vats_deployment_password}}
        VATS_VOLDRIVER_ADDRESS:           {{vats_voldriver_address}}
        VATS_VOLUME_NAME:                 fake-volume
      params:
        <<: *vats-params
        REXRAY_RELEASE_NAME:              ci-vats-scaleio-rexray-boshrelease
        SCALEIO_ENDPOINT:                 {{scaleio_endpoint}}
        SCALEIO_INSECURE:                 {{scaleio_insecure}}
        SCALEIO_MDM_IPS:                  {{scaleio_mdm_ips}}
        SCALEIO_PASSWORD:                 {{scaleio_password}}
        SCALEIO_STORAGE_POOL_NAME:        {{scaleio_storage_pool_name}}
        SCALEIO_USERNAME:                 {{scaleio_username}}
        SCALEIO_VERSION:                  {{scaleio_version}}
        STORAGE_SERVICE_TYPE:             scaleio
        VATS_DEPLOYMENT_IP:               {{scaleio_vats_deployment_ip}}
        VATS_DEPLOYMENT_NAME:             ci-scaleio-vats
      run:
        path: rexray-boshrelease/ci/tasks/vats.rb

- name: isilon-vats
  serial: true
  plan:
  - aggregate:
    - {trigger: true, get: rexray-boshrelease}
    - {trigger: true, get: volman}
  - task: vats
    config:
      <<: *docker
      inputs:
      - name: rexray-boshrelease
      - name: volman
      params:
        <<: *vats-params
        ISILON_DATA_SUBNET:                   {{isilon_data_subnet}}
        ISILON_ENDPOINT:                      {{isilon_endpoint}}
        ISILON_INSECURE:                      {{isilon_insecure}}
        ISILON_PASSWORD:                      {{isilon_password}}
        ISILON_USERNAME:                      {{isilon_username}}
        ISILON_VOLUME_PATH:                   {{isilon_volume_path}}
        REXRAY_RELEASE_NAME:                  ci-vats-isilon-rexray-boshrelease
        STORAGE_SERVICE_TYPE:                 isilon
        VATS_DEPLOYMENT_IP:                   {{isilon_vats_deployment_ip}}
        VATS_DEPLOYMENT_NAME:                 ci-isilon-vats
      run:
        path: rexray-boshrelease/ci/tasks/vats.rb

- name: scaleio-integration
  serial: true
  plan:
  - aggregate:
    - {trigger: true,       get: cf-persist-service-broker}
  - task: integration
    config:
      <<: *docker
      default-params: &integration-params
        BROKER_PASSWORD:                      {{broker_password}}
        BROKER_USERNAME:                      {{broker_username}}
        EMC_SERVICE_NAME:                     {{emc_service_name}}
        EMC_SERVICE_UUID:                     {{emc_service_uuid}}
        INSECURE:                             true
        LIBSTORAGE_URI:                       {{libstorage_uri}}
        PARSED_INSTANCE_ID:                   {{parsed_instance_id}}
        STORAGE_POOL_NAME:                    {{scaleio_storage_pool_name}}
        TEST_INSTANCE_ID:                     {{test_instance_id}}
        PORT:                                 9000
      params:
        <<: *integration-params
        DIEGO_DRIVER_SPEC:                    {{diego_driver_spec_scaleio}}
        LIB_STOR_SERVICE:                     {{lib_stor_service_scaleio}}
        TEST_SIZE:                            8
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh

- name: isilon-integration
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
  - task: integration
    config:
      <<: *docker
      params:
        <<: *integration-params
        DIEGO_DRIVER_SPEC:                    {{diego_driver_spec_isilon}}
        LIB_STOR_SERVICE:                     {{lib_stor_service_isilon}}
        TEST_SIZE:                            0
      inputs:
      - name: cf-persist-service-broker
      run:
        path: cf-persist-service-broker/ci/tasks/integration.sh

- name: deploy-cells
  serial: true
  plan:
  - aggregate:
    - get: rexray-boshrelease
      trigger: true
      passed: [isilon-vats, scaleio-vats]
    - get: scaleio-sdc-boshrelease
      trigger: true
      passed: [scaleio-vats]
    - get: cf-persist-service-broker
      trigger: true
      passed: [isilon-integration, scaleio-integration]
  - task: scale-diego
    config:
      <<: *docker
      params:
        BOSH_DIRECTOR_PUBLIC_IP:      {{bosh_director_public_ip}}
        BOSH_PASSWORD:                {{bosh_password}}
        BOSH_USER:                    {{bosh_user}}
        DIEGO_CELL_IPS:               {{diego_cell_ips}}
        DIEGO_DEPLOYMENT_NAME:        {{diego_deployment_name}}
        SCALEIO_MDM_IPS:              {{scaleio_mdm_ips}}
      inputs:
      - name: cf-persist-service-broker
      - name: rexray-boshrelease
      - name: scaleio-sdc-boshrelease
      run:
        path: cf-persist-service-broker/ci/tasks/deploy-cells.sh

- name: scaleio-lifecycle
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [deploy-cells]
    - get: lifecycle-app
  - task: lifecycle
    config:
      <<: *docker
      default-params: &lifecycle-params
        BROKER_NAME:              {{broker_name}}
        BROKER_PASSWORD:          {{broker_password}}
        BROKER_USERNAME:          {{broker_username}}
        CF_ENDPOINT:              {{cf_endpoint}}
        CF_ORG:                   {{cf_org}}
        CF_PASSWORD:              {{cf_password}}
        CF_SERVICE:               {{emc_service_name}}
        CF_SPACE:                 {{cf_space}}
        CF_USERNAME:              {{cf_username}}
        EMC_SERVICE_NAME:         {{emc_service_name}}
        EMC_SERVICE_UUID:         {{emc_service_uuid}}
        INSECURE:                 true
        LIBSTORAGE_URI:           {{libstorage_uri}}
        LIFECYCLE_APP_NAME:       {{lifecycle_app_name}}
      params:
        <<: *lifecycle-params
        DIEGO_DRIVER_SPEC:        {{diego_driver_spec_scaleio}}
        LIB_STOR_SERVICE:         {{lib_stor_service_scaleio}}
      inputs:
      - name: cf-persist-service-broker
      - name: lifecycle-app
      run:
        path: cf-persist-service-broker/ci/tasks/scaleio-lifecycle.sh

- name: isilon-lifecycle
  serial: true
  serial_groups: [lifecycle]
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [deploy-cells]
    - get: lifecycle-app
  - task: lifecycle
    config:
      <<: *docker
      params:
        <<: *lifecycle-params
        DIEGO_DRIVER_SPEC:        {{diego_driver_spec_isilon}}
        LIB_STOR_SERVICE:         {{lib_stor_service_isilon}}
        LIFECYCLE_APP_MEMORY:     {{lifecycle_app_memory}}
        NUM_DIEGO_CELLS:          {{num_diego_cells}}
      inputs:
      - name: cf-persist-service-broker
      - name: lifecycle-app
      run:
        path: cf-persist-service-broker/ci/tasks/isilon-lifecycle.sh

- name: promote-broker
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      trigger: true
      passed: [isilon-lifecycle, scaleio-lifecycle]
    - get: persist-version
      trigger: false
      params: {bump: major}
  - task: promote
    config:
      <<: *docker
      inputs:
      - name: cf-persist-service-broker
      - name: persist-version
      outputs:
      - name: promote
      run:
        path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
      params:
        GITHUB_USER:              {{github_user}}
        GITHUB_EMAIL:             {{github_email}}
        REPO_NAME:                cf-persist-service-broker
  - put: cf-persist-service-broker-out
    params: {repository: promote/cf-persist-service-broker, rebase: true, tag_prefix: "v", tag: promote/integer_version}
  - put: persist-version
    params: {file: persist-version/number}

- name: promote-rexray
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      passed: [isilon-lifecycle, scaleio-lifecycle]
    - get: rexray-boshrelease
      trigger: true
      passed: [deploy-cells]
    - get: rexray-version
      params: {bump: major}
  - task: promote
    config:
      <<: *docker
      inputs:
      - name: cf-persist-service-broker
      - name: rexray-boshrelease
      - name: rexray-version
      outputs:
      - name: promote
      run:
        path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
      params:
        GITHUB_USER:              {{github_user}}
        GITHUB_EMAIL:             {{github_email}}
        REPO_NAME:                rexray-boshrelease
  - put: rexray-boshrelease-out
    params: {repository: promote/rexray-boshrelease, rebase: true, tag_prefix: "v", tag: promote/integer_version}
  - put: rexray-version
    params: {file: rexray-version/number}


- name: promote-scaleio-sdc
  serial: true
  plan:
  - aggregate:
    - get: cf-persist-service-broker
      passed: [isilon-lifecycle, scaleio-lifecycle]
    - get: scaleio-sdc-boshrelease
      trigger: true
      passed: [deploy-cells]
    - get: scaleio-sdc-version
      params: {bump: major}
  - task: promote
    config:
      <<: *docker
      inputs:
      - name: cf-persist-service-broker
      - name: scaleio-sdc-boshrelease
      - name: scaleio-sdc-version
      outputs:
      - name: promote
      run:
        path: cf-persist-service-broker/ci/tasks/promote-candidate.sh
      params:
        GITHUB_USER:              {{github_user}}
        GITHUB_EMAIL:             {{github_email}}
        REPO_NAME:                scaleio-sdc-boshrelease
  - put: scaleio-sdc-boshrelease-out
    params: {repository: promote/scaleio-sdc-boshrelease, rebase: true, tag_prefix: "v", tag: promote/integer_version}
  - put: scaleio-sdc-version
    params: {file: scaleio-sdc-version/number}

resources:
- name: cf-persist-service-broker
  type: git
  source:
    uri: https://github.com/EMC-Dojo/cf-persist-service-broker.git
    branch: master
    skip_ssl_verification: true

- name: cf-persist-service-broker-out
  type: git
  default-github: &github-secrets
    username: {{github_user}}
    password: {{github_password}}
    skip_ssl_verification: true
  source:
    uri: https://github.com/EMC-Dojo/cf-persist-service-broker.git
    branch: master
    <<: *github-secrets

- name: persist-version
  type: semver
  default-s3: &s3-secrets
    access_key_id:     {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
  source:
    key:               number
    bucket:            {{s3_cf_persist_sb_bucket_name}}
    <<: *s3-secrets

- name: lifecycle-app
  type: git
  source:
    uri: https://github.com/EMC-dojo/kitty.git
    branch: master
    <<: *github-secrets

- name: scaleio-sdc-boshrelease
  type: git
  source:
    uri: https://github.com/EMC-Dojo/ScaleIO-SDC-Bosh-Release.git
    branch: master
    skip_ssl_verification: true

- name: scaleio-sdc-boshrelease-out
  type: git
  source:
    uri: https://github.com/EMC-Dojo/ScaleIO-SDC-Bosh-Release.git
    branch: master
    <<: *github-secrets

- name: scaleio-sdc-version
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_scaleio_sdc_bucket_name}}
    <<: *s3-secrets

- name: rexray-boshrelease
  type: git
  source:
    uri: https://github.com/EMC-Dojo/rexray-boshrelease.git
    branch: master
    skip_ssl_verification: true

- name: rexray-boshrelease-out
  type: git
  source:
    uri: https://github.com/EMC-Dojo/rexray-boshrelease.git
    branch: master
    <<: *github-secrets

- name: rexray-version
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_rexray_bucket_name}}
    <<: *s3-secrets

- name: volman
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/volman
    skip_ssl_verification: true
